<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb6ee4c17fc5d592686896f747be60545
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'Quagga\\Extension\\FileManager\\' => 29,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Quagga\\Extension\\FileManager\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb6ee4c17fc5d592686896f747be60545::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb6ee4c17fc5d592686896f747be60545::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb6ee4c17fc5d592686896f747be60545::$classMap;

        }, null, ClassLoader::class);
    }
}
